name = "Klimakoffer"
uuid = "2a3da7d0-32ba-46a6-a7d5-86c91f8fabb4"
authors = ["Gregor Gassner <ggassner@uni-koeln.de", "Johannes Markert <jmarkert@math.uni-koeln.de>", "Andrés Rueda-Ramírez <aruedara@uni-koeln.de", "Michael Schlottke-Lakemper <michael@sloede.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Requires = "1.1"
UnPack = "1.0.2"
julia = "1.6"
